// ═══ TEMPLATE LIBRARY + KEYWORD MATCHING ENGINE ═══

export interface NodeDetails { project?: string; region?: string; serviceAccount?: string; iamRoles?: string; encryption?: string; monitoring?: string; retry?: string; alerting?: string; cost?: string; troubleshoot?: string; guardrails?: string; compliance?: string; notes?: string }
export interface DiagNode { id: string; name: string; icon?: string | null; subtitle?: string; zone: "sources" | "cloud" | "consumers"; x: number; y: number; details?: NodeDetails }
export interface EdgeSecurity { transport: string; auth: string; classification: string; private: boolean }
export interface DiagEdge { id: string; from: string; to: string; label?: string; subtitle?: string; step: number; security?: EdgeSecurity; crossesBoundary?: boolean }
export interface Threat { id: string; target: string; stride: string; severity: string; title: string; description: string; impact: string; mitigation: string; compliance?: string | null }
export interface Diagram { title: string; subtitle?: string; nodes: DiagNode[]; edges: DiagEdge[]; threats?: Threat[] }
export interface Template { id: string; name: string; icon: string; description: string; tags: string[]; diagram: Diagram }

// ── KEYWORD MATCHER ───────────────────────────────
export function matchTemplate(input: string): Template | null {
  const q = input.toLowerCase();
  let best: Template | null = null, bestScore = 0;
  for (const t of TEMPLATES) {
    let score = 0;
    for (const tag of t.tags) {
      if (q.includes(tag)) score += tag.length; // longer matches = higher confidence
    }
    if (score > bestScore) { bestScore = score; best = t; }
  }
  return bestScore >= 4 ? best : null; // minimum 4 chars matched
}

// ═══ TEMPLATE 1: STREAMING ANALYTICS ══════════════
const STREAMING: Diagram = {
  title: "Streaming Analytics Pipeline",
  subtitle: "Real-time event processing from sources through GCP into analytics and serving",
  nodes: [
    { id: "src_app", name: "Application", icon: null, subtitle: "Event Producer", zone: "sources", x: 80, y: 160, details: { notes: "Primary application producing business events" } },
    { id: "src_mobile", name: "Mobile App", icon: null, subtitle: "User Events", zone: "sources", x: 80, y: 300, details: { notes: "iOS/Android clickstream and user actions" } },
    { id: "src_iot", name: "IoT Devices", icon: null, subtitle: "Sensor Data", zone: "sources", x: 80, y: 440, details: { notes: "Telemetry from edge devices" } },
    { id: "apigee", name: "Apigee", icon: "apigee_api_platform", subtitle: "API Gateway", zone: "cloud", x: 320, y: 160,
      details: { project: "", region: "us-central1", serviceAccount: "sa-apigee@PROJECT.iam", iamRoles: "roles/apigee.apiAdminV2", encryption: "TLS 1.3 termination", monitoring: "API latency P99 < 200ms, error rate, request volume", retry: "Client retry with backoff. 429 rate limiting at 1000 req/s.", alerting: "Error rate > 5% → PagerDuty P2\nLatency P99 > 500ms → Slack P2", cost: "~$3/M API calls", troubleshoot: "Check Apigee Analytics → error breakdown by proxy.\nDebug trace for specific failing requests.\nCheck backend health if 502/503.", guardrails: "OAuth 2.0 required, rate limit per client ID, request body size max 10MB, IP allowlisting for admin APIs", compliance: "SOC2" } },
    { id: "pubsub", name: "Pub/Sub", icon: "pubsub", subtitle: "Event Bus", zone: "cloud", x: 320, y: 300,
      details: { project: "", region: "us-central1", serviceAccount: "sa-pubsub@PROJECT.iam", iamRoles: "roles/pubsub.publisher (producers), roles/pubsub.subscriber (consumers)", encryption: "Google-managed encryption at rest + in transit", monitoring: "Oldest unacked message age, publish rate (msgs/sec), subscription backlog size, dead letter queue depth", retry: "Automatic exponential backoff (min 10s, max 600s).\nDead letter topic after 5 failed delivery attempts.\n7-day message retention for replay.", alerting: "Backlog age > 5min → Slack P2\nDead letter count > 0 → PagerDuty P1\nPublish error rate > 1% → Slack P2", cost: "$40/TB ingested. Optimize: batch publish up to 1000 msgs/request, use message filtering.", troubleshoot: "Backlog growing → check consumer (Dataflow) health, check if subscriber is acking.\nDead letters → check message format, consumer error logs.\nHigh latency → check push endpoint response time.", guardrails: "Schema Registry for message validation, ordering key on entity_id, message dedup by ID", compliance: "SOC2" } },
    { id: "dataflow", name: "Dataflow", icon: "dataflow", subtitle: "Stream Processor", zone: "cloud", x: 540, y: 220,
      details: { project: "", region: "us-central1", serviceAccount: "sa-dataflow@PROJECT.iam", iamRoles: "roles/dataflow.worker, roles/bigquery.dataEditor, roles/storage.objectCreator", encryption: "CMEK via Cloud KMS for temp data and shuffle", monitoring: "System lag (seconds behind real-time), data freshness, elements processed/sec, worker CPU/memory utilization, autoscaler events", retry: "At-least-once processing with checkpointing every 30s.\nAutoscale: min 1, max 20 workers.\nFailed elements → side output to error topic.", alerting: "System lag > 60s → PagerDuty P1 (pipeline falling behind)\nWorker errors > 10/min → Slack P2\nAutoscaling at max → PagerDuty P2 (capacity risk)", cost: "Streaming: $0.069/vCPU-hr + $0.003/GB-hr.\nBatch: FlexRS 60% discount.\nTip: right-size workers, use n1-standard-2 for most jobs.", troubleshoot: "High lag → increase max workers or check for hot keys.\nOOM → increase worker memory type or fix GroupByKey skew.\nStuck → check Dataflow UI for stuck stage, look at worker logs.", guardrails: "Private IPs only (no public workers), VPC-SC perimeter, Workload Identity (no SA keys)", compliance: "SOC2" } },
    { id: "dlp", name: "Cloud DLP", icon: "cloud_natural_language_api", subtitle: "Privacy Scanner", zone: "cloud", x: 540, y: 400,
      details: { project: "", serviceAccount: "sa-dlp@PROJECT.iam", iamRoles: "roles/dlp.user, roles/dlp.inspectTemplatesReader", monitoring: "Findings per scan, PII types detected, scan latency", retry: "Retry on 429/503 with backoff. Async for large datasets.", alerting: "High-risk PII (SSN, credit card) found → PagerDuty P1\nScan failures → Slack P2", cost: "$1-3/GB inspected. Optimize: sample 10% of data, use stored infoType detectors.", troubleshoot: "False positives → tune likelihood threshold, add custom exclusion rules.\nMissing PII → add custom infoTypes for domain-specific patterns.\nSlow scans → reduce inspection template scope.", guardrails: "Inspect ALL data BEFORE storing in warehouse. De-identify before ML training. Column-level masking in BigQuery.", compliance: "HIPAA, GDPR, CCPA, SOC2" } },
    { id: "gcs", name: "Cloud Storage", icon: "cloud_storage", subtitle: "Data Lake (Bronze)", zone: "cloud", x: 740, y: 160,
      details: { project: "", region: "us-central1", serviceAccount: "sa-storage@PROJECT.iam", iamRoles: "roles/storage.objectCreator (writers), roles/storage.objectViewer (readers)", encryption: "CMEK via Cloud KMS, key rotation every 90 days", monitoring: "Object count, total size, request count by type, egress volume", retry: "Client-side retry with exponential backoff on 5xx. Resumable uploads for large objects.", alerting: "Storage > 10TB → budget alert P3\nUnexpected SA access → security alert P1", cost: "Standard: $0.020/GB/mo. Lifecycle: Nearline after 30d ($0.010), Coldline after 90d ($0.004), Archive after 365d ($0.0012).", troubleshoot: "Permission denied → check IAM bindings + VPC-SC perimeter.\nSlow uploads → use parallel composite uploads, check network.\n403 on cross-project → check org policy constraints.", guardrails: "Bucket Lock for compliance retention, Object Versioning enabled, VPC-SC perimeter, no public access (uniform bucket-level IAM)", compliance: "SOC2" } },
    { id: "bigquery", name: "BigQuery", icon: "bigquery", subtitle: "Warehouse (Silver/Gold)", zone: "cloud", x: 740, y: 320,
      details: { project: "", region: "us-central1", serviceAccount: "sa-bq@PROJECT.iam", iamRoles: "roles/bigquery.dataEditor (ETL writes), roles/bigquery.dataViewer (dashboards), roles/bigquery.jobUser (query execution)", encryption: "CMEK via Cloud KMS. Column-level security on PII columns via policy tags.", monitoring: "Slot utilization %, bytes processed per query, streaming buffer size, query count, table row count freshness", retry: "Streaming inserts: retry on 503/500 with exponential backoff.\nBatch loads: Cloud Composer retry (3 attempts, 5min delay).\nQuery failures: automatic retry on transient errors.", alerting: "Slot utilization > 80% → Slack P3 (capacity planning)\nSingle query > $100 → PagerDuty P2\nStreaming insert errors > 1% → PagerDuty P1\nData freshness > 1hr → Slack P2", cost: "On-demand: $6.25/TB queried. Flat-rate: $0.04/slot-hr (predictable).\nBI Engine: $25.50/GB/mo for sub-second cache.\nTip: partition by date, cluster by high-cardinality columns.", troubleshoot: "Slow queries → check INFORMATION_SCHEMA.JOBS_BY_PROJECT, look for full scans, add partitioning.\nHigh cost → audit top 10 queries by bytes scanned.\nStreaming lag → check Dataflow output, BQ streaming buffer metrics.", guardrails: "Authorized views for row-level security. Column-level access controls via policy tags. Audit logs on all data access. No EXPORT DATA without approval.", compliance: "SOC2, HIPAA (with BAA)" } },
    { id: "looker", name: "Looker", icon: "looker", subtitle: "Dashboards", zone: "cloud", x: 940, y: 180,
      details: { project: "", serviceAccount: "sa-looker@PROJECT.iam", iamRoles: "roles/bigquery.dataViewer", encryption: "TLS in transit, Looker-managed at rest", monitoring: "Dashboard load time, query count, cache hit rate, user sessions", alerting: "Dashboard errors > 5% → Slack P2\nCache hit rate < 50% → Slack P3", cost: "Platform license + per-user seats. Enable BI Engine for sub-second queries ($25.50/GB/mo).", troubleshoot: "Slow dashboards → check underlying BQ query. Enable aggregate awareness.\nNo data → check Looker connection credentials.\nStale data → check PDT build schedule.", guardrails: "SSO via SAML/OIDC, row-level permissions via user attributes, disable CSV download for sensitive data, content access controls", compliance: "SOC2" } },
    { id: "cloudrun", name: "Cloud Run", icon: "cloud_run", subtitle: "Data API", zone: "cloud", x: 940, y: 340,
      details: { project: "", region: "us-central1", serviceAccount: "sa-api@PROJECT.iam", iamRoles: "roles/run.invoker (callers), roles/bigquery.dataViewer", encryption: "TLS auto-provisioned, CMEK for container images in Artifact Registry", monitoring: "Request count, latency P50/P95/P99, instance count, memory utilization, cold start rate", retry: "Cloud Run auto-retries on 503. Client side: circuit breaker pattern + exponential backoff.", alerting: "Latency P99 > 2s → Slack P2\n5xx error rate > 1% → PagerDuty P1\nCold start rate > 10% → Slack P3", cost: "Per request + vCPU-second + GiB-second. Set min-instances=1 to avoid cold starts (~$15/mo).\nTip: optimize container startup time, use connection pooling.", troubleshoot: "High latency → check cold starts (increase min instances). Check BQ query time.\n503 errors → check concurrency limit (default 80), increase or add instances.\nOOM → increase memory limit, check for memory leaks.", guardrails: "Binary Authorization (only signed images), VPC connector (no direct internet egress), IAM invoker authentication, container scanning in Artifact Registry", compliance: "SOC2" } },
    { id: "composer", name: "Composer", icon: "cloud_scheduler", subtitle: "Orchestrator", zone: "cloud", x: 400, y: 530,
      details: { project: "", region: "us-central1", serviceAccount: "sa-composer@PROJECT.iam", iamRoles: "roles/composer.worker, roles/composer.environmentAndStorageObjectViewer", monitoring: "DAG success/failure rate, task duration, scheduler heartbeat, worker pod utilization", retry: "Task-level: 3 retries with 5min delay. DAG-level: SLA miss detection.\nDead-letter handling for permanently failed tasks.", alerting: "DAG failure → PagerDuty P1\nSLA miss (pipeline late) → Slack P2\nScheduler heartbeat missing → PagerDuty P1", cost: "Small env: ~$350-500/mo. Medium: ~$800/mo.\nTip: use triggerer for deferrable operators to reduce worker cost.", troubleshoot: "DAG stuck → check task logs in Airflow UI, look for upstream dependency.\nWorker OOM → scale environment or optimize task memory.\nScheduler lag → check DB utilization, upgrade environment size.", guardrails: "Private IP environment, Secret Manager for all connections (no hardcoded creds), RBAC for DAG access", compliance: "SOC2" } },
    { id: "monitoring", name: "Monitoring", icon: "cloud_monitoring", subtitle: "Observability", zone: "cloud", x: 620, y: 530,
      details: { monitoring: "Centralized dashboard: pipeline lag, throughput (events/sec), error rates, data freshness, cost burn rate, SLO burn rate", alerting: "P1 → PagerDuty (pipeline down, data loss risk)\nP2 → Slack #data-alerts (degraded performance, high latency)\nP3 → Email (cost threshold, capacity planning)", cost: "Free for GCP metrics (150+ built-in). Custom metrics: $0.258/metric/mo after 2500 free.\nTip: use log-based metrics instead of custom where possible.", troubleshoot: "Metrics missing → check metric scope, ensure services are in monitored project.\nDashboard not updating → check metric ingestion delay (up to 3min for some).\nAlerts not firing → verify notification channel + check alert condition logic.", guardrails: "Alert on alert silence (meta-monitoring). Every P1 alert has a linked runbook. Quarterly alert review to prune noise.", compliance: "SOC2" } },
    { id: "logging", name: "Cloud Logging", icon: "cloud_logging", subtitle: "Audit Trail", zone: "cloud", x: 840, y: 530,
      details: { monitoring: "Log volume (GiB/day), error log rate, audit access patterns, log-based metrics", alerting: "Unexpected admin action → Security alert P1\nLog volume spike > 2x normal → Slack P3 (cost risk)", cost: "$0.50/GiB ingested after 50GiB/mo free. Route verbose logs to GCS ($0.02/GB/mo) instead.\nTip: exclude debug logs via log router, keep only WARN+ for expensive sources.", troubleshoot: "Missing logs → check log router exclusion filters.\nHigh cost → audit log sources, add exclusion filters for noisy services.\nCan't find entries → check log scope, use advanced query syntax.", guardrails: "Log sinks to BigQuery for long-term analysis. Locked log buckets for compliance retention (cannot delete). Organization-level audit log collection.", compliance: "SOC2, HIPAA (audit trail requirement)" } },
    { id: "con_analysts", name: "Analysts", icon: null, subtitle: "BI Consumers", zone: "consumers", x: 1140, y: 180, details: { notes: "Business analysts accessing Looker dashboards via SSO" } },
    { id: "con_apps", name: "Applications", icon: null, subtitle: "API Consumers", zone: "consumers", x: 1140, y: 340, details: { notes: "Downstream applications calling data API via OAuth 2.0" } },
  ],
  edges: [
    { id: "e1", from: "src_app", to: "apigee", label: "Business Events", subtitle: "HTTPS / OAuth 2.0 + API Key", step: 1, security: { transport: "TLS 1.3", auth: "OAuth 2.0 + API Key", classification: "confidential", private: false }, crossesBoundary: true },
    { id: "e2", from: "src_mobile", to: "pubsub", label: "Clickstream Events", subtitle: "HTTPS / Firebase Auth JWT", step: 2, security: { transport: "TLS 1.3", auth: "Firebase Auth JWT", classification: "internal", private: false }, crossesBoundary: true },
    { id: "e3", from: "src_iot", to: "pubsub", label: "Sensor Telemetry", subtitle: "MQTT over TLS / X.509 device cert", step: 3, security: { transport: "TLS 1.2 (MQTT)", auth: "X.509 device certificate", classification: "internal", private: false }, crossesBoundary: true },
    { id: "e4", from: "apigee", to: "pubsub", label: "Validated Events", subtitle: "Internal gRPC / Workload Identity", step: 4, security: { transport: "Internal gRPC", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e5", from: "pubsub", to: "dataflow", label: "Event Stream", subtitle: "Push subscription / Workload Identity", step: 5, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e6", from: "dataflow", to: "gcs", label: "Raw Events (Bronze)", subtitle: "GCS client library / Workload Identity", step: 6, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e7", from: "dataflow", to: "bigquery", label: "Processed Records (Silver)", subtitle: "BQ Storage Write API / Workload Identity", step: 7, security: { transport: "Internal gRPC", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e8", from: "bigquery", to: "looker", label: "Analytics Queries", subtitle: "BigQuery API / OAuth 2.0 (SSO)", step: 8, security: { transport: "HTTPS", auth: "OAuth 2.0 via SSO", classification: "internal", private: true }, crossesBoundary: false },
    { id: "e9", from: "bigquery", to: "cloudrun", label: "Query Results", subtitle: "BigQuery API / Workload Identity", step: 9, security: { transport: "Internal", auth: "Workload Identity", classification: "internal", private: true }, crossesBoundary: false },
    { id: "e10", from: "looker", to: "con_analysts", label: "Dashboards & Reports", subtitle: "HTTPS / SAML SSO + MFA", step: 10, security: { transport: "TLS 1.3", auth: "SAML SSO + MFA", classification: "internal", private: false }, crossesBoundary: true },
    { id: "e11", from: "cloudrun", to: "con_apps", label: "JSON API Responses", subtitle: "HTTPS / OAuth 2.0 Bearer Token", step: 11, security: { transport: "TLS 1.3", auth: "OAuth 2.0 Bearer Token", classification: "internal", private: false }, crossesBoundary: true },
  ],
  threats: [
    { id: "T1", target: "e1", stride: "S", severity: "high", title: "API key compromise", description: "Stolen or leaked API key allows unauthorized event injection into pipeline", impact: "Malicious or corrupted data enters the pipeline, affecting downstream analytics", mitigation: "Rotate API keys quarterly. IP allowlisting on Apigee. Anomaly detection on event patterns (sudden volume/schema change).", compliance: "SOC2" },
    { id: "T2", target: "pubsub", stride: "D", severity: "medium", title: "Event bus flooding", description: "Malicious or buggy producer floods Pub/Sub with millions of events", impact: "Dataflow overwhelmed, increased cost, potential data delays", mitigation: "Pub/Sub quotas per publisher SA. Apigee rate limiting at edge. Dataflow autoscale max limit. Budget alerts.", compliance: "SOC2" },
    { id: "T3", target: "bigquery", stride: "I", severity: "high", title: "Over-permissive BQ access", description: "Overly broad IAM roles expose sensitive columns to unauthorized analysts", impact: "PII/financial data leaked to unauthorized users, compliance violation", mitigation: "Column-level security via policy tags. Authorized views instead of direct table access. Quarterly IAM access reviews. VPC-SC perimeter.", compliance: "SOC2, HIPAA" },
    { id: "T4", target: "e10", stride: "S", severity: "medium", title: "Dashboard session hijack", description: "SSO session token stolen via XSS or session fixation attack on Looker", impact: "Unauthorized access to analytics dashboards containing business-sensitive data", mitigation: "Content Security Policy headers. Short session TTL (4hr). IP-bound sessions. MFA enforcement. Session logging.", compliance: "SOC2" },
  ],
};

// ═══ TEMPLATE 2: CDC MIGRATION ════════════════════
const CDC_MIGRATION: Diagram = {
  title: "Cross-Cloud CDC Migration Pipeline",
  subtitle: "Real-time CDC replication from AWS RDS / on-prem databases to GCP BigQuery via Datastream",
  nodes: [
    { id: "src_rds", name: "AWS RDS", icon: null, subtitle: "PostgreSQL Source", zone: "sources", x: 80, y: 180, details: { notes: "AWS RDS PostgreSQL with logical replication enabled (wal_level=logical). Source of truth for transactional data." } },
    { id: "src_s3", name: "AWS S3", icon: null, subtitle: "Data Lake Files", zone: "sources", x: 80, y: 330, details: { notes: "Historical data exports, CSV/Parquet files for batch backfill." } },
    { id: "src_oracle", name: "On-Prem Oracle", icon: null, subtitle: "Legacy Database", zone: "sources", x: 80, y: 470, details: { notes: "Oracle 12c+ with LogMiner or XStream enabled for CDC capture." } },
    { id: "vpn", name: "Cloud VPN", icon: "cloud_vpn", subtitle: "Encrypted Tunnel", zone: "cloud", x: 300, y: 180,
      details: { project: "", region: "us-central1", encryption: "IPSec with IKEv2, AES-256-GCM", monitoring: "Tunnel status (up/down), bandwidth utilization, packet loss", retry: "Automatic tunnel re-establishment on failure", alerting: "Tunnel down → PagerDuty P1\nBandwidth > 80% → Slack P2", cost: "~$0.075/hr per tunnel + egress. Interconnect for >500Mbps.", troubleshoot: "Tunnel down → check peer gateway health, verify IKE config.\nSlow → check bandwidth capacity, consider Interconnect.\nPacket loss → check MTU settings, fragmentation.", guardrails: "Dedicated VPN gateway per environment. Pre-shared key in Secret Manager. Regular rotation.", compliance: "SOC2" } },
    { id: "interconnect", name: "Interconnect", icon: "cloud_interconnect", subtitle: "Dedicated Link", zone: "cloud", x: 300, y: 470,
      details: { project: "", region: "us-central1", encryption: "MACsec at Layer 2, application-layer TLS", monitoring: "Link status, bandwidth utilization, light levels", alerting: "Link down → PagerDuty P1", cost: "10Gbps: ~$1,700/mo. 100Gbps: ~$17,000/mo. + partner fees.", troubleshoot: "Link down → check with colo/partner. Light levels off → physical layer issue.", guardrails: "Redundant attachments in different edge availability domains.", compliance: "SOC2, HIPAA (dedicated circuit)" } },
    { id: "datastream", name: "Datastream", icon: "datastream", subtitle: "CDC Capture", zone: "cloud", x: 500, y: 180,
      details: { project: "", region: "us-central1", serviceAccount: "sa-datastream@PROJECT.iam", iamRoles: "roles/datastream.admin, roles/storage.objectCreator", encryption: "TLS in transit, Google-managed at rest", monitoring: "CDC lag (seconds behind source), throughput (events/sec), unsupported events count", retry: "Automatic retry on transient errors. Resumes from last checkpoint on restart.", alerting: "CDC lag > 5min → PagerDuty P1\nUnsupported events > 0 → Slack P2\nStream unhealthy → PagerDuty P1", cost: "Free for first 500GB/mo processed. Then $0.10/GB. Very cost-effective for CDC.", troubleshoot: "CDC lag increasing → check source DB load, network bandwidth (VPN/Interconnect).\nUnsupported events → check for DDL changes, unsupported column types.\nStream paused → check IAM permissions, network connectivity.", guardrails: "Allowlist specific tables (don't replicate everything). Filter out system tables. Schema validation on target.", compliance: "SOC2" } },
    { id: "sts", name: "Transfer Service", icon: "cloud_storage", subtitle: "S3 Batch Transfer", zone: "cloud", x: 500, y: 330,
      details: { project: "", serviceAccount: "sa-sts@PROJECT.iam", monitoring: "Transfer job status, bytes transferred, objects transferred", retry: "Automatic retry on failure. Incremental: only new/changed objects.", alerting: "Transfer failure → Slack P2\nTransfer > 2x expected duration → Slack P3", cost: "Free service. Pay only for GCS storage + S3 egress fees.", troubleshoot: "Failed → check IAM role on S3 bucket. Verify cross-cloud credentials in Secret Manager.\nSlow → network bandwidth, object count (many small files = slow).", guardrails: "Use AWS IAM role (not access keys) via Workload Identity Federation. Encrypt at rest in both clouds.", compliance: "SOC2" } },
    { id: "gcs_land", name: "Cloud Storage", icon: "cloud_storage", subtitle: "Landing Zone", zone: "cloud", x: 680, y: 180,
      details: { project: "", region: "us-central1", encryption: "CMEK, 90-day rotation", monitoring: "Object count, new objects/hour, total size", retry: "Lifecycle policy moves failed processing to retry prefix", alerting: "No new objects in 1hr (during business hours) → Slack P2", cost: "$0.020/GB/mo Standard. Lifecycle: Nearline 30d, delete after 90d.", troubleshoot: "No new objects → check Datastream health.\nPermission denied → verify Datastream SA has objectCreator.", guardrails: "Separate bucket per source. Object versioning. VPC-SC perimeter.", compliance: "SOC2" } },
    { id: "dataflow", name: "Dataflow", icon: "dataflow", subtitle: "ETL Processor", zone: "cloud", x: 680, y: 380,
      details: { project: "", region: "us-central1", serviceAccount: "sa-dataflow@PROJECT.iam", iamRoles: "roles/dataflow.worker, roles/bigquery.dataEditor, roles/storage.objectViewer", encryption: "CMEK for temp/shuffle data", monitoring: "Elements processed, system lag, data freshness, worker utilization", retry: "At-least-once. Failed records → dead letter table in BigQuery.", alerting: "System lag > 120s → PagerDuty P1\nDead letter records > 0 → Slack P2", cost: "Streaming: $0.069/vCPU-hr. Batch: FlexRS 60% off.", troubleshoot: "High lag → check for hot keys in GroupByKey, increase workers.\nSchema errors → check source DDL changes, update Beam pipeline.\nOOM → increase worker machine type.", guardrails: "Private IPs only, VPC-SC, Workload Identity. Schema validation on read.", compliance: "SOC2" } },
    { id: "catalog", name: "Data Catalog", icon: "data_catalog", subtitle: "Metadata & Lineage", zone: "cloud", x: 680, y: 530,
      details: { project: "", monitoring: "Tagged assets count, policy tag coverage", cost: "Free for GCP resource metadata. Custom entries: $0.01/entry/mo.", troubleshoot: "Missing entries → check automatic discovery settings.", guardrails: "Mandatory tags for data classification, owner, freshness SLA.", compliance: "SOC2" } },
    { id: "bigquery", name: "BigQuery", icon: "bigquery", subtitle: "Target Warehouse", zone: "cloud", x: 890, y: 250,
      details: { project: "", region: "us-central1", serviceAccount: "sa-bq@PROJECT.iam", iamRoles: "roles/bigquery.dataEditor (ETL), roles/bigquery.dataViewer (consumers)", encryption: "CMEK, column-level security on PII", monitoring: "Row count freshness, slot utilization, query volume, streaming buffer", retry: "Streaming: retry 503 with backoff. Batch: Composer retry 3x.", alerting: "Data freshness > 15min → PagerDuty P2\nSlot utilization > 80% → Slack P3", cost: "On-demand $6.25/TB. Flat-rate for predictable workloads.", troubleshoot: "Stale data → check Dataflow/Datastream. Missing rows → check dead letter table.\nSlow → check partition pruning, clustering.", guardrails: "Authorized views, column-level ACL, audit all access.", compliance: "SOC2, HIPAA" } },
    { id: "looker", name: "Looker", icon: "looker", subtitle: "Migration Dashboard", zone: "cloud", x: 1050, y: 180,
      details: { monitoring: "CDC lag dashboard, data quality scores, migration progress", guardrails: "SSO, row-level permissions", compliance: "SOC2" } },
    { id: "cloudrun", name: "Cloud Run", icon: "cloud_run", subtitle: "Data API", zone: "cloud", x: 1050, y: 340,
      details: { project: "", region: "us-central1", monitoring: "Request count, latency P99", guardrails: "Binary Auth, VPC connector", compliance: "SOC2" } },
    { id: "composer", name: "Composer", icon: "cloud_scheduler", subtitle: "Orchestrator", zone: "cloud", x: 500, y: 530, details: { monitoring: "DAG success rate", alerting: "DAG failure → PagerDuty P1", cost: "~$400/mo", compliance: "SOC2" } },
    { id: "monitoring", name: "Monitoring", icon: "cloud_monitoring", subtitle: "Observability", zone: "cloud", x: 890, y: 530, details: { monitoring: "CDC lag, data freshness SLOs, pipeline throughput", alerting: "P1 → PagerDuty, P2 → Slack", compliance: "SOC2" } },
    { id: "con_dashboard", name: "Stakeholders", icon: null, subtitle: "Migration Tracking", zone: "consumers", x: 1230, y: 180, details: { notes: "Project stakeholders tracking migration progress via Looker" } },
    { id: "con_api", name: "Applications", icon: null, subtitle: "Migrated Apps", zone: "consumers", x: 1230, y: 340, details: { notes: "Applications switching from AWS RDS reads to GCP API" } },
  ],
  edges: [
    { id: "e1", from: "src_rds", to: "vpn", label: "CDC WAL Stream", subtitle: "PostgreSQL logical replication / TLS + VPN", step: 1, security: { transport: "IPSec VPN + TLS", auth: "DB credentials in Secret Manager", classification: "confidential", private: true }, crossesBoundary: true },
    { id: "e2", from: "src_s3", to: "sts", label: "Historical Files", subtitle: "HTTPS / Workload Identity Federation", step: 2, security: { transport: "TLS 1.3", auth: "Workload Identity Federation (no keys)", classification: "confidential", private: false }, crossesBoundary: true },
    { id: "e3", from: "src_oracle", to: "interconnect", label: "Oracle CDC (LogMiner)", subtitle: "Dedicated Interconnect / mTLS", step: 3, security: { transport: "Dedicated circuit + TLS", auth: "mTLS + DB credentials", classification: "confidential", private: true }, crossesBoundary: true },
    { id: "e4", from: "vpn", to: "datastream", label: "Encrypted CDC", subtitle: "Private network / Workload Identity", step: 4, security: { transport: "Private network", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e5", from: "datastream", to: "gcs_land", label: "CDC JSON Files", subtitle: "GCS API / Workload Identity", step: 5, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e6", from: "sts", to: "gcs_land", label: "Transferred Files", subtitle: "Internal / Workload Identity", step: 6, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e7", from: "gcs_land", to: "dataflow", label: "Raw Data for ETL", subtitle: "GCS notification → Dataflow / WI", step: 7, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e8", from: "dataflow", to: "bigquery", label: "Clean Records", subtitle: "BQ Storage Write API / WI", step: 8, security: { transport: "Internal gRPC", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e9", from: "bigquery", to: "looker", label: "Migration Analytics", subtitle: "BQ API / OAuth SSO", step: 9, security: { transport: "HTTPS", auth: "OAuth 2.0 SSO", classification: "internal", private: true }, crossesBoundary: false },
    { id: "e10", from: "bigquery", to: "cloudrun", label: "API Queries", subtitle: "BQ API / Workload Identity", step: 10, security: { transport: "Internal", auth: "Workload Identity", classification: "internal", private: true }, crossesBoundary: false },
    { id: "e11", from: "looker", to: "con_dashboard", label: "Progress Reports", subtitle: "HTTPS / SAML SSO", step: 11, security: { transport: "TLS 1.3", auth: "SAML SSO", classification: "internal", private: false }, crossesBoundary: true },
    { id: "e12", from: "cloudrun", to: "con_api", label: "API Responses", subtitle: "HTTPS / OAuth 2.0", step: 12, security: { transport: "TLS 1.3", auth: "OAuth 2.0", classification: "internal", private: false }, crossesBoundary: true },
  ],
  threats: [
    { id: "T1", target: "e1", stride: "T", severity: "high", title: "VPN tunnel intercept", description: "Attacker compromises VPN tunnel or performs man-in-the-middle on CDC stream", impact: "Sensitive database records exposed in transit", mitigation: "IPSec + application-layer TLS. Rotate pre-shared keys quarterly. Monitor tunnel anomalies.", compliance: "SOC2" },
    { id: "T2", target: "datastream", stride: "I", severity: "high", title: "CDC data tampering", description: "Unauthorized modification of CDC events in landing zone before ETL processing", impact: "Corrupted data in warehouse, incorrect business decisions", mitigation: "Object versioning on GCS. Checksum validation in Dataflow. Immutable landing bucket.", compliance: "SOC2" },
    { id: "T3", target: "e2", stride: "S", severity: "medium", title: "Cross-cloud credential theft", description: "AWS IAM credentials for S3 access stolen or leaked", impact: "Unauthorized access to source data lake", mitigation: "Use Workload Identity Federation (no static keys). Short-lived tokens only. Audit access logs.", compliance: "SOC2" },
    { id: "T4", target: "bigquery", stride: "I", severity: "high", title: "Schema drift breaks pipeline", description: "Source DB schema change (DDL) breaks CDC or ETL without warning", impact: "Data loss or pipeline failure during migration", mitigation: "Schema validation in Dataflow. DDL change alerts from Datastream. Data Catalog lineage tracking.", compliance: "SOC2" },
  ],
};

// ═══ TEMPLATE 3: RAG / GENAI ══════════════════════
const RAG_GENAI: Diagram = {
  title: "RAG / GenAI Application",
  subtitle: "Document ingestion, embedding, vector search, and grounded generation with Vertex AI Gemini",
  nodes: [
    { id: "src_drive", name: "Google Drive", icon: null, subtitle: "Documents", zone: "sources", x: 80, y: 160, details: { notes: "Team documents, policies, knowledge base articles" } },
    { id: "src_confluence", name: "Confluence", icon: null, subtitle: "Wiki Pages", zone: "sources", x: 80, y: 300, details: { notes: "Engineering wiki, runbooks, product specs via REST API" } },
    { id: "src_upload", name: "File Uploads", icon: null, subtitle: "User PDFs", zone: "sources", x: 80, y: 440, details: { notes: "User-uploaded PDFs, DOCX, TXT files via web UI" } },
    { id: "functions", name: "Cloud Functions", icon: "cloud_functions", subtitle: "Webhook Handler", zone: "cloud", x: 300, y: 160,
      details: { project: "", region: "us-central1", serviceAccount: "sa-ingest@PROJECT.iam", iamRoles: "roles/cloudfunctions.invoker, roles/pubsub.publisher", encryption: "TLS in transit", monitoring: "Invocation count, error rate, latency", retry: "Automatic retry on failure (3 attempts)", alerting: "Error rate > 5% → Slack P2", cost: "Free tier: 2M invocations/mo. Then $0.40/M.", troubleshoot: "Failed → check function logs. Timeout → increase timeout or optimize.\nAuth error → check Drive/Confluence OAuth token refresh.", guardrails: "Min permissions, 60s timeout, 256MB memory max", compliance: "SOC2" } },
    { id: "pubsub", name: "Pub/Sub", icon: "pubsub", subtitle: "Document Queue", zone: "cloud", x: 300, y: 300,
      details: { project: "", region: "us-central1", monitoring: "Message backlog, processing rate", retry: "Dead letter after 5 attempts", alerting: "Backlog > 100 messages → Slack P2", cost: "$40/TB", guardrails: "Schema validation for document metadata", compliance: "SOC2" } },
    { id: "docai", name: "Document AI", icon: "document_ai", subtitle: "PDF Extraction", zone: "cloud", x: 500, y: 160,
      details: { project: "", region: "us", serviceAccount: "sa-docai@PROJECT.iam", monitoring: "Pages processed, extraction accuracy", retry: "Retry on 429/503 with backoff", alerting: "Extraction failures > 5% → Slack P2", cost: "~$0.01-0.10/page depending on processor type", troubleshoot: "Poor extraction → try different processor (OCR vs form vs invoice).\nSlow → check page count, use async processing for >5 pages.", guardrails: "Human-in-loop for confidence < 80%. Discard unreadable pages.", compliance: "SOC2" } },
    { id: "chunker", name: "Cloud Run", icon: "cloud_run", subtitle: "Text Chunker", zone: "cloud", x: 500, y: 300,
      details: { project: "", region: "us-central1", serviceAccount: "sa-chunker@PROJECT.iam", monitoring: "Documents processed, chunks created, avg chunk size", retry: "Pub/Sub delivery retry. Failed docs → dead letter.", alerting: "Processing errors > 5% → Slack P2", cost: "Per request. ~$15/mo with min instances.", troubleshoot: "Chunks too large → adjust recursive splitter params (512 tokens, 50 overlap).\nMissing content → check Document AI extraction quality.\nSlow → increase concurrency or instances.", guardrails: "Max chunk size 512 tokens, 50 token overlap. Metadata preserved per chunk (source, page, section).", compliance: "SOC2" } },
    { id: "embeddings", name: "Vertex AI", icon: "vertexai", subtitle: "Embeddings API", zone: "cloud", x: 700, y: 230,
      details: { project: "", region: "us-central1", serviceAccount: "sa-embed@PROJECT.iam", iamRoles: "roles/aiplatform.user", encryption: "Google-managed, data not stored", monitoring: "Embedding requests/sec, latency, token count", retry: "Retry on 429 with backoff. Batch for bulk processing.", alerting: "Latency > 500ms → Slack P3", cost: "text-embedding-004: $0.025/1K chars. ~$0.00002 per chunk.", troubleshoot: "Rate limited → reduce batch size, add backoff.\nDimension mismatch → verify model version matches vector store config.", guardrails: "Use text-embedding-004 (768 dims). Batch up to 250 texts/request.", compliance: "SOC2" } },
    { id: "vectordb", name: "Cloud SQL", icon: "cloud_sql", subtitle: "pgvector Store", zone: "cloud", x: 700, y: 400,
      details: { project: "", region: "us-central1", serviceAccount: "sa-vectordb@PROJECT.iam", iamRoles: "roles/cloudsql.client", encryption: "CMEK, encrypted connections (SSL required)", monitoring: "Connection count, query latency, storage size, index performance", retry: "Connection pooling with PgBouncer. Auto-reconnect on failure.", alerting: "Connection count > 80% limit → Slack P2\nQuery latency > 100ms → Slack P3", cost: "db-custom-2-4096: ~$50/mo. Storage: $0.17/GB/mo.", troubleshoot: "Slow search → check HNSW index, increase ef_search. Rebuild index if stale.\nConnection errors → check connection pool, max_connections limit.\nOut of storage → archive old embeddings.", guardrails: "Private IP only (no public). SSL required. IAM database authentication. Regular VACUUM.", compliance: "SOC2" } },
    { id: "orchestrator", name: "Cloud Run", icon: "cloud_run", subtitle: "RAG Orchestrator", zone: "cloud", x: 900, y: 230,
      details: { project: "", region: "us-central1", serviceAccount: "sa-rag@PROJECT.iam", iamRoles: "roles/run.invoker, roles/aiplatform.user, roles/cloudsql.client", monitoring: "Query count, latency P99, retrieval quality (MRR), generation cost", retry: "Retry Gemini calls on 503. Circuit breaker after 3 failures.", alerting: "P99 > 5s → PagerDuty P2\nGemini errors > 5% → PagerDuty P1\nCost per query > $0.10 → Slack P3", cost: "Cloud Run: ~$30/mo. Gemini: ~$0.0005-0.005/query. Total ~$50-200/mo.", troubleshoot: "Bad answers → check retrieval quality (MRR), tune top_k.\nSlow → cache frequent queries in Memorystore.\nHigh cost → reduce max_tokens, cache, filter unnecessary context.", guardrails: "Max context: 10 chunks per query. Max response: 1000 tokens. System prompt isolated from user input. Response grounding verification.", compliance: "SOC2" } },
    { id: "dlp", name: "Cloud DLP", icon: "cloud_natural_language_api", subtitle: "PII Guard", zone: "cloud", x: 700, y: 80,
      details: { monitoring: "PII findings per query", alerting: "PII in user prompt → log + strip", cost: "$1-3/GB inspected", guardrails: "Scan user input BEFORE sending to Gemini. Strip PII from retrieved context. Never include PII in generation.", compliance: "GDPR, SOC2" } },
    { id: "gemini", name: "Gemini", icon: "vertexai", subtitle: "LLM Generation", zone: "cloud", x: 900, y: 400,
      details: { project: "", region: "us-central1", monitoring: "Tokens in/out, latency, safety filter triggers, grounding score", retry: "Retry on 503/429. Fallback to cached response if persistent failure.", alerting: "Safety filter rate > 5% → review prompts\nCost > daily budget → throttle", cost: "Gemini 1.5 Flash: $0.075/1M input tokens, $0.30/1M output. Pro: 7x more.", troubleshoot: "Bad answers → improve system prompt, add few-shot examples.\nHallucination → enable grounding, add citation verification.\nSlow → use Flash instead of Pro, reduce context length.", guardrails: "System prompt injection protection. Output safety filters enabled. Grounding with citations. Temperature 0.1 for factual, 0.7 for creative.", compliance: "SOC2" } },
    { id: "memorystore", name: "Memorystore", icon: "memorystore", subtitle: "Response Cache", zone: "cloud", x: 1050, y: 320,
      details: { project: "", region: "us-central1", monitoring: "Cache hit rate, memory utilization", cost: "Redis Basic 1GB: ~$35/mo. Hit rate > 30% = net savings.", guardrails: "Cache key = query embedding similarity (>0.95). TTL 1hr for factual, 15min for dynamic.", compliance: "SOC2" } },
    { id: "firebase", name: "Identity Platform", icon: "identity_platform", subtitle: "User Auth", zone: "cloud", x: 1050, y: 160,
      details: { monitoring: "Auth success rate, active users", guardrails: "MFA required for admin. Rate limit failed logins. Session TTL 4hr.", compliance: "SOC2" } },
    { id: "monitoring", name: "Monitoring", icon: "cloud_monitoring", subtitle: "Observability", zone: "cloud", x: 550, y: 530, details: { monitoring: "Retrieval quality, latency, token cost, user satisfaction", alerting: "P1 → PagerDuty, P2 → Slack", compliance: "SOC2" } },
    { id: "logging", name: "Cloud Logging", icon: "cloud_logging", subtitle: "Prompt Audit", zone: "cloud", x: 800, y: 530,
      details: { monitoring: "Every prompt + response logged for audit", guardrails: "Redact PII before logging. Locked retention.", compliance: "SOC2" } },
    { id: "con_users", name: "End Users", icon: null, subtitle: "Chat Interface", zone: "consumers", x: 1230, y: 230, details: { notes: "Users interacting via React web UI with streaming responses" } },
  ],
  edges: [
    { id: "e1", from: "src_drive", to: "functions", label: "Doc Change Events", subtitle: "Drive API webhook / OAuth 2.0", step: 1, security: { transport: "TLS 1.3", auth: "OAuth 2.0", classification: "confidential", private: false }, crossesBoundary: true },
    { id: "e2", from: "src_confluence", to: "functions", label: "Page Updates", subtitle: "REST API / API Token", step: 2, security: { transport: "TLS 1.3", auth: "API Token", classification: "confidential", private: false }, crossesBoundary: true },
    { id: "e3", from: "src_upload", to: "pubsub", label: "Uploaded Files", subtitle: "HTTPS / Firebase Auth", step: 3, security: { transport: "TLS 1.3", auth: "Firebase Auth JWT", classification: "confidential", private: false }, crossesBoundary: true },
    { id: "e4", from: "functions", to: "pubsub", label: "Doc Events", subtitle: "Internal / Workload Identity", step: 4, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e5", from: "pubsub", to: "docai", label: "PDFs for Extraction", subtitle: "Push sub / Workload Identity", step: 5, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e6", from: "pubsub", to: "chunker", label: "Text for Chunking", subtitle: "Push sub / Workload Identity", step: 6, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e7", from: "docai", to: "chunker", label: "Extracted Text", subtitle: "Internal / Workload Identity", step: 7, security: { transport: "Internal", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e8", from: "chunker", to: "embeddings", label: "Text Chunks", subtitle: "Vertex API / Workload Identity", step: 8, security: { transport: "Internal gRPC", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e9", from: "embeddings", to: "vectordb", label: "Vectors + Metadata", subtitle: "PostgreSQL / Workload Identity", step: 9, security: { transport: "SSL required", auth: "IAM DB auth", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e10", from: "orchestrator", to: "vectordb", label: "Similarity Search", subtitle: "SQL query / IAM DB auth", step: 10, security: { transport: "SSL", auth: "IAM DB auth", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e11", from: "orchestrator", to: "gemini", label: "Context + Query", subtitle: "Vertex API / Workload Identity", step: 11, security: { transport: "Internal gRPC", auth: "Workload Identity", classification: "confidential", private: true }, crossesBoundary: false },
    { id: "e12", from: "orchestrator", to: "con_users", label: "Streamed Response", subtitle: "HTTPS SSE / Firebase Auth", step: 12, security: { transport: "TLS 1.3", auth: "Firebase Auth JWT", classification: "internal", private: false }, crossesBoundary: true },
  ],
  threats: [
    { id: "T1", target: "orchestrator", stride: "T", severity: "critical", title: "Prompt injection", description: "Malicious user crafts input that overrides system prompt, causing unintended behavior", impact: "LLM ignores safety instructions, leaks system prompt or internal data", mitigation: "Separate system/user prompts. Input validation + sanitization. Prompt injection classifier before Gemini call. Output filtering.", compliance: "SOC2" },
    { id: "T2", target: "e3", stride: "I", severity: "high", title: "Malicious document upload", description: "User uploads document containing embedded malware or adversarial content", impact: "Poisoned knowledge base returns incorrect/harmful answers", mitigation: "Scan uploads with malware scanner. Content moderation on extracted text. Source attribution on all answers.", compliance: "SOC2" },
    { id: "T3", target: "gemini", stride: "I", severity: "high", title: "Hallucination / confabulation", description: "Gemini generates plausible but factually incorrect information", impact: "Users act on incorrect information, trust erosion", mitigation: "Grounding with retrieved context. Citation verification. Confidence scoring. 'I don't know' fallback for low confidence.", compliance: "SOC2" },
    { id: "T4", target: "vectordb", stride: "I", severity: "medium", title: "Stale embeddings", description: "Source documents updated but embeddings not re-generated", impact: "RAG returns outdated information", mitigation: "Webhook-triggered re-indexing. Daily freshness check. Source timestamp in metadata.", compliance: "SOC2" },
  ],
};

// ═══ TEMPLATE REGISTRY ════════════════════════════
export const TEMPLATES: Template[] = [
  {
    id: "streaming-analytics",
    name: "Streaming Analytics",
    icon: "📊",
    description: "Real-time event processing with Pub/Sub, Dataflow, and BigQuery",
    tags: ["streaming", "stream", "real-time", "realtime", "real time", "event", "events", "pub/sub", "pubsub", "dataflow", "analytics", "clickstream", "iot", "sensor", "event-driven", "event driven", "kafka", "stream processing", "pipeline", "ingest", "ingestion"],
    diagram: STREAMING,
  },
  {
    id: "cdc-migration",
    name: "CDC Migration",
    icon: "🔄",
    description: "Cross-cloud CDC replication from AWS/Oracle to GCP BigQuery",
    tags: ["cdc", "migration", "migrate", "replicate", "replication", "datastream", "aws to gcp", "aws", "cross-cloud", "cross cloud", "rds", "oracle", "mysql", "postgresql", "postgres", "database migration", "data migration", "hybrid", "vpn", "interconnect", "transfer"],
    diagram: CDC_MIGRATION,
  },
  {
    id: "rag-genai",
    name: "RAG / GenAI",
    icon: "🤖",
    description: "Document RAG chatbot with Vertex AI Gemini and vector search",
    tags: ["rag", "genai", "gen ai", "generative", "chatbot", "chat bot", "assistant", "copilot", "llm", "gemini", "openai", "gpt", "embedding", "embeddings", "vector", "vector search", "pgvector", "document", "knowledge base", "ai assistant", "conversational", "question answering", "qa"],
    diagram: RAG_GENAI,
  },
];
